# Generated by Django 4.2.17 on 2025-04-08 13:32

import apps.utils.fields.image_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shortcut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(max_length=100, verbose_name="Address")),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Titre de la page"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="Description du site"
                    ),
                ),
                (
                    "icon",
                    apps.utils.fields.image_field.CustomImageField(verbose_name="Logo"),
                ),
            ],
        ),
    ]
