# Generated by Django 4.2.17 on 2025-04-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortcut", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortcut",
            name="description_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Description du site"
            ),
        ),
        migrations.AddField(
            model_name="shortcut",
            name="description_fr",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Description du site"
            ),
        ),
        migrations.AddField(
            model_name="shortcut",
            name="title_en",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Titre de la page"
            ),
        ),
        migrations.AddField(
            model_name="shortcut",
            name="title_fr",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Titre de la page"
            ),
        ),
    ]
